# Generated by Django 3.1.7 on 2021-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chantier_se',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pk_depose_debut', models.IntegerField()),
                ('pk_depose_fin', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='info_chantier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.CharField(max_length=30)),
                ('nbr_voies_travail', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_debut_chantier', models.DateField()),
                ('date_fin_chantier', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.TextField(max_length=100)),
                ('prenom', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('habilitation', models.TextField(max_length=100)),
                ('nom', models.TextField(max_length=100)),
                ('date_depart', models.DateField()),
                ('date_arrive', models.DateField()),
                ('fonction', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='procedure_s9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_prog_jour', models.IntegerField()),
                ('nom_phase', models.CharField(max_length=30)),
                ('trx_nuit', models.BooleanField()),
                ('DFV', models.BooleanField()),
                ('continuite_elec', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('h_fin', models.TimeField()),
                ('date_debut_trx', models.DateField()),
                ('pk_fin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ct_Tx', models.CharField(max_length=30)),
                ('etat_surface_rail', models.BooleanField()),
                ('pk_debut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('h_debut', models.TimeField()),
                ('GEq', models.BooleanField()),
                ('RCT', models.BooleanField()),
                ('indice_CtTx', models.CharField(max_length=30)),
                ('Voie', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ttx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pk_fin', models.IntegerField()),
                ('fonction', models.TextField(max_length=100)),
                ('pk_deput', models.IntegerField()),
                ('nom_ttx', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pk_engagment', models.IntegerField()),
                ('pk_degagment', models.IntegerField()),
            ],
        ),
    ]
