# Generated by Django 3.1.7 on 2021-04-06 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_base_chantier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_chantier',
            name='nom_chantier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
